apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-local-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: "test.local"
  secretName: test-local-root-ca-secret
  duration: 8760h         # 1 год
  renewBefore: 360h       # обновлять за 15 дней до окончания
  issuerRef:
    name: ca-selfsign
    kind: Issuer

