resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 20m
    memory: 50Mi

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 20m
      memory: 50Mi

cainjector:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 20m
      memory: 50Mi
