- name: Ensure group "wheel" exists
  group:
    name: wheel
    state: present
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: add users
  user:
        name: "{{ item }}"
        groups: wheel
        shell: /bin/bash
        append: yes
  with_items:
        - ansible
        #- testuser
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: add users
  user:
        name: "{{ item }}"
        groups: wheel
        shell: /bin/bash
        append: yes
  with_items:
        - ansible
        #- testuser
  when: ansible_distribution in ['RedHat', 'CentOS', 'Rocky']

- name: Set authorized key took from file for users
  authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/{{ item }}.id_rsa.pub') }}"
  with_items:
        - ansible
        #- testuser
