- name: Install default packages
  yum:
        name: "{{item}}"
        state: present
  with_items:
        - sudo
        - telnet
        - htop
        - bind-utils
        - net-tools
        - vim
        - nano
        - tcpdump
        - ntp
        - libselinux-python
        - wget
  when: (ansible_distribution_major_version == "7")


- name: Install additional packages in Centos/Rhel 7
  yum:
        name: "{{ item }}"
        state: present
  with_items:
        - iptables
        - iptables-services
  when: (ansible_distribution_major_version == "7")

- name: Delete firewalld service
  yum:
         name: firewalld
         state: absent
  when: (ansible_distribution_major_version == "7")




- name: Install default packages debian
  apt:
    name:
      - sudo
      - telnet
      - htop
      - dnsutils
      - net-tools
      - vim
      - nano
      - tcpdump
      - ntp
      - python3-selinux
      - wget
    state: present
  when: ansible_distribution == 'Debian'

- name: Install additional packages in Debian 11
  apt:
    name:
      - iptables
      - iptables-persistent
    state: present
  when: ansible_distribution == 'Debian' 

- name: Delete ufw service
  apt:
    name: ufw
    state: absent
  when: ansible_distribution == 'Debian' 
