- name: Install essential packages
  yum:
    name:
      - sshpass
      - sudo
      - telnet
      - htop
      - bind-utils
      - net-tools
      - vim
      - nano
      - tcpdump
      - ntp
      - ntpdate
      - libselinux-python
      - wget
      - rsync
    state: latest
  when: ansible_distribution in ['RedHat', 'CentOS']


- name: Install additional packages
  yum:
    name:
      - iptables
      - iptables-services
    state: latest
  when: ansible_distribution in ['RedHat', 'CentOS']


- name: Delete firewalld service
  yum:
         name: firewalld
         state: absent
  when: (ansible_distribution_major_version == "7")



- name: Install default packages debian
  apt:
    name:
      - thin-provisioning-tools
      - sshpass
      - sudo
      - telnet
      - htop
      - dnsutils
      - net-tools
      - vim
      - nano
      - tcpdump
      - ntp
      - ntpdate
      - python3-selinux
      - wget
      - rsync
      - software-properties-common
    state: present
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Install additional packages in Debian 11
  apt:
    name:
      - iptables
      - iptables-persistent
    state: present
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Delete ufw service
  apt:
    name: ufw
    state: absent
  when: ansible_distribution in ['Debian', 'Ubuntu']
