- name: Copy sshd_config to remote host
  template: src=/etc/ansible/roles/new_server/templates/sshd_config{{ ansible_distribution_major_version }} dest=/etc/ssh/sshd_config  mode='600'
  notify:
        - restart sshd

