  - name: put patroni.service systemd unit
    template:
      src: ../templates/patroni.service 
      dest: /etc/systemd/system/patroni.service
      backup: yes

  - name: Reload daemon definitions
    command: /usr/bin/systemctl daemon-reload
    tags: patroni

