---
- import_tasks: ntp.yml
  tags: update time 

- import_tasks: install_etcd.yml
  tags: install etcd package
  when: inventory_hostname in groups['etcd']

- import_tasks: install_postgres.yml
  tags: install postgres package
  when:
    - inventory_hostname in groups['patroni']

- import_tasks: install_patroni.yml
  tags: install patroni
  when: 
    - inventory_hostname in groups['patroni']

- import_tasks: install_haproxy.yml
  tags: install haproxy
  when: inventory_hostname in groups['patroni']



#- import_tasks: install_pgbouncer.yml
#  tags: install pgbouncer
#  when: 
#    - inventory_hostname in groups['balance']
#    - proxy
#- import_tasks: install_pgbouncer-without-proxy.yml
#  tags: install pgbouncer
#  when:
#    - inventory_hostname in groups['balance']
#    - not proxy

#- import_tasks: add_pgbouncer_config.yml
#  tags: add pgbouncer config
#  when: inventory_hostname in groups['balance']


- import_tasks: install_keepalived.yml
  tags: install keepalived
  when: inventory_hostname in groups['patroni']


