- name: Installing GitLab
  become: yes
  yum:
    name: gitlab-ce
    state: present
    disable_gpg_check: yes
  tags:
    - gitlab

#- name: GitLab reconfigure
#  become: yes
#  shell: /bin/gitlab-ctl reconfigure
#  tags:
#    - gitlab
#  notify: start_gitlab

- name: Display Password
  debug:
    msg: "Login credentials for the GitLab admin are  root / 5iveL!fe"
  tags:
    - gitlab

