- name: GitLab password
  become: yes
  shell: cat /etc/gitlab/initial_root_password | grep ^Password
  register: gitlab_password
  when: inventory_hostname in groups['gitlab-server']

- name: gitlab show PASSWORD
  debug:
    var: gitlab_password.stdout_lines
  when: inventory_hostname in groups['gitlab-server']
