version: '3.5'
services:
   node-exporter:
     image: prom/node-exporter
     volumes:
       - /proc:/host/proc:ro
       - /sys:/host/sys:ro
       - /:/rootfs:ro
     command:
       - '--path.procfs=/host/proc'
       - '--path.sysfs=/host/sys'
       - '--path.rootfs=/rootfs'
       - '--collector.filesystem.mount-points-exclude'
       - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
     expose:
       - 9100
     restart: always
     network_mode: host
 
   vmagent:
     image: victoriametrics/vmagent
     volumes:
       - ./data/vmagentdata:/vmagentdata
       - ./prometheus.yml:/etc/prometheus/prometheus.yml
     command:
       - '--promscrape.config=/etc/prometheus/prometheus.yml'
       - '--remoteWrite.url=http://vmsingle.test.local/api/v1/write'
       - '--remoteWrite.showURL'
       - '--remoteWrite.tlsInsecureSkipVerify=true'
     restart: always
     network_mode: host

