global:
  # как часто опрашивать targets
  scrape_interval: 15s
  # сколько ждать ответа от target
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'node-vault'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.1.103:9100']
