kubelet_custom_flags:
  - "--cpu-manager-policy=static"
  - "--eviction-hard=memory.available<1Gi"
  - "--eviction-minimum-reclaim=memory.available=2Gi"
  - "--eviction-max-pod-grace-period=30"
  - "--system-reserved=memory=1.5Gi,cpu=1"

kube_memory_reserved: 512M
kube_cpu_reserved: 200m

kubeconfig_localhost: true
kubectl_localhost: true

kubelet_status_update_frequency: 10s
kube_controller_node_monitor_grace_period: 20s
kube_controller_node_monitor_period: 30s
kube_controller_pod_eviction_timeout: 30s

kube_controller_memory_limit: 2048M
kube_controller_cpu_limit: 1000m
kube_controller_memory_requests: 1024M
kube_controller_cpu_requests: 500m

kube_scheduler_memory_limit: 1024M
kube_scheduler_cpu_limit: 500m
kube_scheduler_memory_requests: 512M
kube_scheduler_cpu_requests: 300m

kube_apiserver_cpu_limit: 1000m
kube_apiserver_memory_limit: 5000M
kube_apiserver_cpu_requests: 500m
kube_apiserver_memory_requests: 1024M

flannel_cpu_limit: 500m
flannel_cpu_requests: 300m
