- name: Install mariadb 5.5
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb
    - mariadb-server
    - mariadb-libs
    - mariadb-devel

- name: Start the mariadb service
  service: name=mariadb state=started enabled=true

- name: Change mariadb root password and keep track in 
  shell: |
    mysql -uroot -e "SET PASSWORD FOR root@'localhost' = PASSWORD('{{database_pass}}'); flush privileges;"
  register: change_temp_pass
  notify: restart mariadb

- meta: flush_handlers
- debug:
    var: change_temp_pass


#- name: "Ansible  Print a variable"
#  debug:
#    var: "{{item}}"
#  with_items:
#    - database_pass
#    - installdatabase
#    - database
#    - password_match
#  when: "inventory_hostname in groups['mysql']"

