---
# Выполняется только на хостах из группы seaweed_master

- name: Установить пакеты для etcd
  apt:
    name:
      - wget
      - curl
    state: present
    update_cache: yes
  become: yes

- name: Проверить наличие etcd binary
  stat:
    path: /usr/local/bin/etcd
  register: etcd_binary
  become: yes

- name: Скачиваем etcd-архив на хост
  get_url:
    url: "{{ etcd_download_url }}"
    dest: "/tmp/etcd-{{ etcd_version }}.tar.gz"
    mode: '0644'
  when: not etcd_binary.stat.exists
  become: yes

- name: Распаковываем etcd
  unarchive:
    src: "/tmp/etcd-{{ etcd_version }}.tar.gz"
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: ["--strip-components=1"]
    creates: /usr/local/bin/etcd
  when: not etcd_binary.stat.exists
  become: yes

- name: Создать группу etcd
  group:
    name: etcd
    system: yes
  become: yes

- name: Создать пользователя etcd
  user:
    name: etcd
    system: yes
    shell: /sbin/nologin
    group: etcd
  become: yes

- name: Создать директории для etcd
  file:
    path: "{{ item }}"
    state: directory
    owner: etcd
    group: etcd
    mode: '0755'
  loop:
    - "{{ etcd_data_dir }}"
    - "{{ etcd_conf_dir }}"
  become: yes

- name: Деплой конфигурации etcd.conf
  template:
    src: etcd.conf.j2
    dest: "{{ etcd_conf_dir }}/etcd.conf"
    owner: etcd
    group: etcd
    mode: '0644'
  become: yes

- name: Деплой systemd-юнита etcd
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: '0644'
  notify: Reload systemd
  become: yes

- name: Запустить и включить etcd
  systemd:
    name: etcd
    state: started
    enabled: yes
  become: yes

- name: Подождать доступности etcd на 2379
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 2379
    state: started
    timeout: 30
  become: yes
