- name: Проверить наличие weed binary на мастере
  stat:
    path: /usr/local/bin/weed
  register: weed_master_binary
  become: yes

- block:
    - name: Скачиваем SeaweedFS (weed) на мастер
      get_url:
        url: "{{ seaweed_download_url }}"
        dest: "/tmp/seaweedfs-{{ seaweed_version }}.tar.gz"
        mode: '0644'

    - name: Создать временную директорию для распаковки
      file:
        path: "/tmp/seaweedfs-{{ seaweed_version }}"
        state: directory
        mode: '0755'

    - name: Распаковать весь архив во временную папку
      unarchive:
        src: "/tmp/seaweedfs-{{ seaweed_version }}.tar.gz"
        dest: "/tmp/seaweedfs-{{ seaweed_version }}"
        remote_src: yes

    - name: Найти weed-бинарь в распаковке
      find:
        paths: "/tmp/seaweedfs-{{ seaweed_version }}"
        patterns: weed
        file_type: file
      register: weed_find

    - name: Установить weed в /usr/local/bin
      copy:
        src: "{{ weed_find.files[0].path }}"
        dest: /usr/local/bin/weed
        remote_src: yes
        mode: '0755'

    - name: Удалить временную папку распаковки
      file:
        path: "/tmp/seaweedfs-{{ seaweed_version }}"
        state: absent

  when: not weed_master_binary.stat.exists
  become: yes


- name: Создать пользователя seaweedfs
  user:
    name: "{{ seaweed_user }}"
    system: yes
    shell: /sbin/nologin
  become: yes

- name: Создать директорию для master
  file:
    path: "{{ seaweed_master_dir }}"
    state: directory
    owner: "{{ seaweed_user }}"
    group: "{{ seaweed_user }}"
    mode: '0755'
  become: yes

- name: Установить systemd-юнит weed-master
  template:
    src: weed-master.service.j2
    dest: /etc/systemd/system/weed-master.service
  notify:
    - Reload systemd
    - Restart weed-master
  become: yes

- name: Запустить и включить weed-master
  systemd:
    name: weed-master
    state: started
    enabled: yes
  become: yes
