---
- name: Write kubelet config file (non-kubeadm)
  template:
    src: kubelet.standard.env.j2
    dest: "{{ kube_config_dir }}/kubelet.env"
    backup: yes
  when: not kubeadm_enabled
  notify: Node | restart kubelet
  tags:
    - kubelet

- name: write the kubecfg (auth) file for kubelet
  template:
    src: "{{ item }}-kubeconfig.yaml.j2"
    dest: "{{ kube_config_dir }}/{{ item }}-kubeconfig.yaml"
    backup: yes
  with_items:
    - node
    - kube-proxy
  when: not kubeadm_enabled
  notify: Node | restart kubelet
  tags:
    - kubelet

- name: Make sure dynamic kubelet configuration directory is writeable
  file:
    path: "{{ dynamic_kubelet_configuration_dir }}"
    mode: 0600
    state: directory
  when: dynamic_kubelet_configuration
  tags:
    - kubelet

- name: Get the kubeadm version
  command: "{{ bin_dir }}/kubeadm version -o short"
  register: kubeadm_output
  when: kubeadm_enabled
  tags:
    - kubelet
    - kubeadm
  changed_when: false

- name: Set kubelet api version to v1beta1
  set_fact:
    kubeletConfig_api_version: v1beta1
  when:
    - kubeadm_enabled
  tags:
    - kubelet
    - kubeadm

- name: Write kubelet environment config file (kubeadm)
  template:
    src: "kubelet.env.{{ kubeletConfig_api_version }}.j2"
    dest: "{{ kube_config_dir }}/kubelet.env"
    backup: yes
  notify: Node | restart kubelet
  when:
    - kubeadm_enabled
  tags:
    - kubelet
    - kubeadm

- name: Write kubelet config file
  template:
    src: "kubelet-config.{{ kubeletConfig_api_version }}.yaml.j2"
    dest: "{{ kube_config_dir }}/kubelet-config.yaml"
  when:
    - kubeadm_enabled
  notify: Kubelet | restart kubelet
  tags:
    - kubelet
    - kubeadm

- name: Write kubelet systemd init file
  template:
    src: "kubelet.service.j2"
    dest: "/etc/systemd/system/kubelet.service"
    backup: "yes"
  notify: Node | restart kubelet
  tags:
    - kubelet
    - kubeadm

- name: flush_handlers and reload-systemd
  meta: flush_handlers

- name: Enable kubelet
  service:
    name: kubelet
    enabled: yes
    state: started
  tags:
    - kubelet
  notify: Kubelet | restart kubelet
