---
- name: start nfs
  service: name=nfs state=started enabled=yes
  when: ansible_distribution in ['RedHat', 'CentOS']

- name: start nfs
  service: name=nfs-server state=started enabled=yes
  when: inventory_hostname in groups['nfsmaster'] and ansible_distribution in ['Debian', 'Ubuntu']

- name: start rpcbind
  service: name=rpcbind state=restarted enabled=yes
  when: ansible_distribution in ['RedHat', 'CentOS']

