apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: "vaultauth-{{ .Values.vault_secret.secret_name }}"
spec:
  vaultConnectionRef: {{ .Values.vault_secret.vaultConnectionRef }} 
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: {{ .Values.vault_secret.role }}
    serviceAccount: {{ include "common-chart.serviceAccountName" . }}
