apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: "vaultsecret-{{ .Values.vault_secret.secret_name }}"
spec:
  vaultAuthRef: "vaultauth-{{ .Values.vault_secret.secret_name }}"
  mount: {{ .Values.vault_secret.mount }} 
  type: {{ .Values.vault_secret.type }} 
  path:  {{ .Values.vault_secret.path }} 
  refreshAfter: {{ .Values.vault_secret.refreshAfter }} 
  destination:
    create: true
    overwrite: true
    name: {{ .Values.vault_secret.secret_name }} 
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ include "common-chart.fullname" . }}

