apiVersion: v1
kind: Secret
metadata:
  name: argocd-ldap-secret
  namespace: argocd
type: Opaque
stringData:
  # bindDN вашего LDAP‑пользователя
  ldap.bindDN: "uid=argocd,cn=sysaccounts,cn=etc,dc=test,dc=local"
  # bindPW — здесь указываете ваш пароль
  ldap.bindPW: "Secret123"
