global:
  domain: argocd.test.local

configs:
  params:
    server.insecure: true

server:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    extraTls:
      - hosts:
        - argocd.test.local
        # Based on the ingress controller used secret might be optional
        secretName: argocd-tls
  resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 50m
     memory: 64Mi


redis-ha:
  enabled: true
  haproxy:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
  redis:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
  sentinel:
    resources:
     requests:
       memory: 200Mi
       cpu: 100m
     limits:
       memory: 200Mi
       cpu: 500m

controller:
  replicas: 1
  resources:
   limits:
     cpu: 500m
     memory: 512Mi
   requests:
     cpu: 250m
     memory: 150Mi


repoServer:
  replicas: 2
  resources:
   limits:
     cpu: 50m
     memory: 128Mi
   requests:
     cpu: 10m
     memory: 64Mi

applicationSet:
  replicas: 2
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

dex:
  resources:
   limits:
     cpu: 50m
     memory: 64Mi
   requests:
     cpu: 10m
     memory: 32Mi
