---
- name: restart ntpd
  service: name=ntpd state=restarted enabled=yes
  when: ansible_distribution in ['RedHat', 'CentOS']
- name: restart sshd
  service: name=sshd state=restarted enabled=yes
  when: ansible_distribution in ['RedHat', 'CentOS']
- name: restart ntp
  service: name=ntp state=restarted enabled=yes
  when: ansible_distribution == 'Debian'

