---
- name: restart ntpd
  service: name=ntpd state=restarted enabled=yes
  when: ansible_facts['os_family'] == 'RedHat' and  (ansible_facts['distribution'] == 'CentOS' or 'Rocky' in ansible_facts['distribution'])
- name: restart sshd
  service: name=sshd state=restarted enabled=yes
  when: ansible_facts['os_family'] == 'RedHat' and  (ansible_facts['distribution'] == 'CentOS' or 'Rocky' in ansible_facts['distribution'])
- name: restart ntp
  service: name=ntp state=restarted enabled=yes
  when: ansible_distribution == 'Debian'

