- name: Add  logs for proftpd 
  blockinfile:
    dest: /etc/proftpd.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK logs"
    block: |
      LogFormat                       write   "%h %l %u %t "%r" %s %b"
      SystemLog                       /var/log/proftpd/proftpd.log
      TransferLog                     /var/log/proftpd/xfer.log
      ExtendedLog                     /var/log/proftpd/access.log WRITE,READ write
      ExtendedLog                     /var/log/proftpd/auth.log AUTH auth
    state: present

- name: create log files
  file:
      path: "{{item}}"
      state: touch
  with_items:
      - /var/log/proftpd/proftpd.log
      - /var/log/proftpd/xfer.log
      - /var/log/proftpd/access.log
      - /var/log/proftpd/auth.log

