apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultAuth
metadata:
  labels:
    app.kubernetes.io/name: vaultauth
    app.kubernetes.io/instance: vaultauth-sample
    app.kubernetes.io/part-of: vault-secrets-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vault-secrets-operator
  name: vaultauth-app1
  namespace: test
spec:
  vaultConnectionRef: 
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: test-role
    serviceAccount: test-serviceaccaunt

