---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultStaticSecret
metadata:
  namespace: test
  name: vault-secret-app1
spec:
  vaultAuthRef: vaultauth-app1
  mount: test/secret
  type: kv-v1
  name: namespace-test/first-app
  refreshAfter: 10s
  destination:
    create: true
    name: test-secret-k8s
    type: Opaque
  rolloutRestartTargets:
    - kind: Deployment
      name: test-work-test-chart
