- name: Create directories for bricks
  file:
    path: "{{ dir_gluster_master }}/gv01"
    state: directory
    mode: '0755'
  become: true
  become_user: root
  become_method: sudo
  when: inventory_hostname in groups['glustermaster']

- name: Create Gluster volume "{{ name_of_gluster_tom }}".
  gluster_volume:
    state: present
    name: "{{ name_of_gluster_tom }}"
    bricks: >-
      {% for host in groups['glustermaster'] %}
      {{ host }}:{{ dir_gluster_master }}/gv01
      {% if not loop.last %},
      {% endif %}
      {% endfor %}
    replicas: 2
    transport: tcp
    rebalance: yes
    force: yes
  become: true
  become_user: root
  become_method: sudo
  run_once: true
  ignore_errors: true
  when: inventory_hostname == groups['glustermaster'][0]

- name: start gluster volume "{{ name_of_gluster_tom }}"
  gluster_volume:
    state: started
    name: "{{ name_of_gluster_tom }}"
  run_once: true
  when: inventory_hostname in groups['glustermaster']
