- name: Add all hosts and ip to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '{{ hostvars[item].ansible_default_ipv4.address }}.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_hostname }}"
    state: present
  become: yes
  with_items: "{{ groups.glusterfs }}"

- name: save only uniq in /etc/hosts to /etc/hosts2
  shell: "/usr/bin/cat /etc/hosts | /usr/bin/awk '!a[$0]++'  > /etc/hosts2"

- name: save only uniq
  shell: "mv /etc/hosts2 /etc/hosts"

