- name: Set host names
  hostname:
    name: "{{ inventory_hostname }}"
  become: true
  when: inventory_hostname in groups['glustermaster']

- name: Add hosts to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
    state: present
  loop: "{{ groups['glustermaster'] }}"

- name: save only uniq in /etc/hosts to /etc/hosts2
  shell: "/usr/bin/cat /etc/hosts | /usr/bin/awk '!a[$0]++'  > /etc/hosts2"

- name: save only uniq
  shell: "mv /etc/hosts2 /etc/hosts"

