- name: install  grlusterfs client
  yum:
    name:
      - glusterfs-client
    state: latest
  when: 
    - ansible_distribution in ['RedHat', 'CentOS']
    - inventory_hostname in groups['glusterclient']

- name: install  grlusterfs client
  apt:
    name:
      - glusterfs-client
    state: present
  tags:
    - pre-reqs
  when: 
    - ansible_distribution in ['Debian', 'Ubuntu']
    - inventory_hostname in groups['glusterclient']
