- name: install  grlusterfs server
  yum:
    name:
    - glusterfs 
    - glusterfs-libs 
    - glusterfs-server
    state: latest
    force: yes
    allow_downgrade: yes
  notify:
   - Start gluster
  when: 
    - ansible_distribution in ['RedHat', 'CentOS']
    - inventory_hostname in groups['glustermaster']

- name: preinstall debian
  apt:
    name:
      - gnupg2 
      - apt-transport-https 
      - software-properties-common
    state: present
    force: yes
    force_apt_get: yes
  notify:
   - Start gluster
  when: 
    - ansible_distribution in ['Debian', 'Ubuntu']

- name: install  grlusterfs server debian
  apt:
    name:
      - glusterfs-server
    state: present
    force: yes
    force_apt_get: yes
  notify:
   - Start gluster
  when: 
    - ansible_distribution in ['Debian', 'Ubuntu']
    - inventory_hostname in groups['glustermaster']
