- name: get ip brick.
  shell:
    cmd: gluster volume info | grep -i brick1 | awk -F ':' '{print $2}' | tr -d ' '
  run_once: true
  changed_when: false
  register: gluster_brick_ip
  when: inventory_hostname in groups['glustermaster']


- name: Ensure Gluster volume is mounted.
  become: yes
  become_user: root
  mount:
    name: "{{ dir_gluster_client }}"
    src: "localhost:/{{name_of_gluster_tom}}"
    path: "{{dir_gluster_client}}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted
  when: inventory_hostname in groups['glustermaster']

- name: Ensure Gluster volume is mounted to client
  become: yes
  become_user: root
  mount:
    name: "{{ dir_gluster_client }}"
    src: "{{ gluster_brick_ip.stdout }}:/{{name_of_gluster_tom}}"
    path: "{{dir_gluster_client}}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted
  when: inventory_hostname in groups['glusterclient']


