- name: Gather brick IP addresses
  shell: |
    gluster volume info | grep -iE '^Brick[0-9]+:.*' | awk -F ':' '{print $2}' | tr -d ' '
  register: gluster_brick_ips
  run_once: true
  changed_when: false
  when: inventory_hostname in groups['glustermaster']

- name: Ensure Gluster volume is mounted on master
  become: yes
  become_user: root
  mount:
    name: "{{ dir_gluster_client }}"
    src: "{{ groups['glustermaster'] | map('regex_replace', '$', ':/' + name_of_gluster_tom) | join(',') }}"
    path: "{{ dir_gluster_client }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted
  when: inventory_hostname in groups['glustermaster']

- name: Ensure Gluster volume is mounted on clients
  become: yes
  become_user: root
  mount:
    name: "{{ dir_gluster_client }}"
    src: "{{ groups['glustermaster'] | join(',') }}:/{{ name_of_gluster_tom }}"
    path: "{{ dir_gluster_client }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted
  when: inventory_hostname in groups['glusterclient']