- name: install  grlusterfs server
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - glusterfs 
    - glusterfs-libs 
    - glusterfs-server
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  notify:
   - Start gluster
  when: inventory_hostname in groups['glustermaster']
