- name: install  grlusterfs server
  yum:
    name:
    - glusterfs 
    - glusterfs-libs 
    - glusterfs-server
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  notify:
   - Start gluster
  when: 
    - ansible_distribution in ['RedHat', 'CentOS']
    - inventory_hostname in groups['glustermaster']

- name: preinstall debian
  apt:
    name:
      - gnupg2 
      - apt-transport-https 
      - software-properties-common
    state: present
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  notify:
   - Start gluster
  when: 
    - ansible_distribution in ['Debian', 'Ubuntu']

- name: install  grlusterfs server debian
  apt:
    name:
      - glusterfs-server
    state: present
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  notify:
   - Start gluster
  when: 
    - ansible_distribution in ['Debian', 'Ubuntu']
    - inventory_hostname in groups['glustermaster']
