- name: PROXY -----  Check current docker-compose version.
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: PROXY -----  Delete existing docker-compose version if it's different.
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout
- name: PROXY -----  Install Docker Compose (if configured). through proxy "{{ http_proxy }}"
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: 0755
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

- name: PROXY -----  install docker-compose stuff with pip through proxy "{{ http_proxy }}"
  pip:
    name: " {{ item }}"
  with_items:
    - pyyaml
    - docker-py
#    - docker-compose
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
