- name: "add master to swarm cluster"
  become: yes
  become_user: root
  shell:
    cmd:  "{{swarm_master.stdout}}"
  when:
      - "inventory_hostname in groups['swarmmaster']"
      - "'docker-ce' in ansible_facts.packages"
      - "'active' in check_swarm.stdout_lines"


#- name: "Ansible  Print a variable"
#  debug:
#    var: "{{item}}"
#  with_items:
#    - swarm_master.stdout_lines
#    - swarm_worker.stdout_lines
#  when: "'swarm' in check_swarm.stdout_lines"




