- name: Install EPEL repo.
  yum:
   name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
   state: present

- name: Import EPEL GPG key.
  rpm_key:
   key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
   state: present

- name: Add Docker repo
  get_url:
   url: https://download.docker.com/linux/centos/docker-ce.repo
   dest: /etc/yum.repos.d/docer-ce.repo
  become: yes



- name: Check that the /etc/yum.repos.d/kubernetes.repo  exists
  stat:
    path: /etc/yum.repos.d/kubernetes.repo
  register: stat_result

- name: Copy the template repo /etc/yum.repos.d/kubernetes.repo, if it doesnt exist already
  template:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
  when: stat_result.stat.exists == False   
