- name: PROXY ----- delete from yum.conf proxy "{{ http_proxy }}"
  lineinfile: dest=/etc/yum.conf state=absent regexp="{{ http_proxy }}"
              insertafter=EOF line="proxy={{ http_proxy }}"
  ignore_errors: yes


- name: PROXY ----- delete proxy from /etc/environment
  blockinfile:
    dest: /etc/environment
    block: |
      export http_proxy="{{ http_proxy }}"
      export https_proxy="{{ http_proxy }}"
    state: absent




