---
- name: purge docker-compose package
  yum:
    name: docker-compose
    state: absent
  when: ansible_distribution in ['RedHat', 'CentOS']

- name: purge docker-compose package
  apt:
    name: docker-compose
    state: absent
  when: ansible_distribution in ['Debian', 'Ubuntu']
