---
- import_tasks: add-repo-docker.yml
  tags: Add repo docker
  when: not proxy
- import_tasks: proxy-add-repo-docker.yml
  tags: Add repo docker with proxy
  when: proxy
- import_tasks: docker-preinstall.yml
  tags: install packpage fo docker
  when: not proxy
- import_tasks: proxy-docker-preinstall.yml
  tags: install packpage fo docker
  when: proxy
- import_tasks: install-docker.yml
  tags: install docker
  when: not proxy
- import_tasks: proxy-install-docker.yml
  tags: install docker
  when: proxy
- import_tasks: docker-compose-preinstall.yml
  tags: install packpage fo docker-compose
  when: not proxy
- import_tasks: proxy-docker-compose-preinstall.yml
  tags: install packpage fo docker-compose
  when: proxy
- import_tasks: install-docker-compose.yml
  tags: install docker-compose
  when: not proxy
- import_tasks: proxy-install-docker-compose.yml
  tags: install docker-compose
  when: proxy
- import_tasks: docker_proxy.yaml
  tags: use docker proxy
  when: proxy


