- name: default packages for docker through proxy "{{ http_proxy }}"
  yum:
        name: "{{item}}"
        state: present
  with_items:
        - yum-utils 
        - device-mapper-persistent-data
        - lvm2
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

