- name: Install Vault Debian
  apt:
    name:
      - vault
    state: present
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Install Vault Rhell
  yum:
    name:
      - vault
    state: latest
  when: ansible_distribution in ['CentOS', 'RedHat']

- name: Render vault template
  ansible.builtin.template:
    src: vault.hcl.j2
    dest: "/etc/vault.d/vault.hcl"
  vars:
    cluster_addr: "{{ inventory_hostname  }}"
    api_addr: "{{ inventory_hostname  }}"
