- name: install default packages 
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - yum-utils
    - python2-pip
    - yum-plugin-priorities
    - device-mapper-persistent-data
    - lvm2
    - ceph-deploy
#    - ceph-fuse
