---
- name: restart ntpd
  service: name=ntpd state=restarted enabled=yes
- name: restart keepalived
  service: name=keepalived state=restarted enabled=yes
- name: restart haproxy
  service: name=haproxy state=restarted enabled=yes


