---
- name: restart ntpd
  service: name=ntpd state=restarted enabled=yes
- name: restart keepalived
  service: name=keepalived state=restarted enabled=yes
- name: restart haproxy
  service: name=haproxy state=restarted enabled=yes
- name: restart etcd
  service: name=etcd state=restarted enabled=yes
- name: Restart Patroni
  become: true
  service:
    name: patroni
    state: restarted
    enabled: yes
