apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: app-creds
  namespace: app
spec:
  vaultAuthRef: vault-auth-test
  mount: test/secret
  type: kv-v1
  path:  app/first-app
  refreshAfter: 10s
  destination:
    create: true
    overwrite: true
    name: app-secret

