- name: Add PROXY "{{ http_proxy }}" for install "{{ database }}"
  lineinfile: dest=/etc/yum.conf state=present regexp="{{ http_proxy }}"
              insertafter=EOF line="proxy={{ http_proxy }}"
  ignore_errors: yes


- name: PROXY ----- add proxy to /etc/environment
  blockinfile:
    dest: /etc/environment
    block: |
      export http_proxy="{{ http_proxy }}"
      export https_proxy="{{ http_proxy }}"
    state: present

