- name: Add repo for mariadb 10.3
  template:
    src=/etc/ansible/roles/databases/templates/mariadb-10.3.repo
    dest=/etc/yum.repos.d/mariadb-10.3.repo
  when:
#    - "inventory_hostname in groups['mysql']"
    - "'mysql-community-server' not in ansible_facts.packages"
    - "'mariadb-server' not in ansible_facts.packages"
    - "{{ database == 'mariadb10_3' }}"
    - "{{ installdatabase }}"



- name: Install mariadb 10.3
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - MariaDB-server
    - MariaDB-client


- name: Start the mariadb service
  service: name=mariadb state=started enabled=true

- name: Change mariadb root password and keep track in 
  shell: |
    mysql -uroot -e "SET PASSWORD FOR root@'localhost' = PASSWORD('{{database_pass}}'); flush privileges;"
  register: change_temp_pass
  notify: restart mariadb

- meta: flush_handlers
- debug:
    var: change_temp_pass



