apiVersion: v1
kind: Endpoints
metadata: 
  name: glusterfs-cluster
  namespace: kube-system
subsets:
  - addresses:
      #Тут указываем ip наших серверов
      - ip: 192.168.1.109
    ports:
      #Тут просто можно оставить 1, порт роли не играет
      - port: 1
  - addresses:
      - ip: 192.168.1.110
    ports:
      - port: 1
