{{- if .Values.vault_secret.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: "{{ include "common-chart.fullname" . }}-va"
  labels:
    {{- include "common-chart.labels" . | nindent 4 }}
spec:
  vaultConnectionRef: {{ .Values.vault_secret.vaultConnectionRef | default "kube-system/vault-connection" }}
  method: kubernetes
  mount: {{ .Values.vault_secret.authMount | default "kubernetes" }}
  kubernetes:
    role: {{ .Values.vault_secret.role | default "ns-scoped-read" }}
    serviceAccount: {{ include "common-chart.serviceAccountName" . }}
    {{- /* безопасно формируем audiences: берём из values, иначе дефолт */ -}}
    {{- $aud := default (list "https://kubernetes.default.svc") (get .Values.vault_secret "audiences") }}
    audiences:
    {{- range $aud }}
      - {{ . | quote }}
    {{- end }}
{{- end }}
