apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth-test
  namespace: test
spec:
  vaultConnectionRef: kube-system/vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: test-role
    serviceAccount: test-serviceaccount
