apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: app-db-creds-test
  namespace: test
spec:
  vaultAuthRef: vault-auth-test
  mount: test/secret
  type: kv-v1
  path:  namespace-test/first-app
  refreshAfter: 10s
  destination:
    create: true
    overwrite: true
    name: test-secret-k8s
