{{- if .Values.vault_secret.enabled }}

{{/* Требуемый full path: "<ns>/service/<leaf>" */}}
{{- $full := required "values.vault_secret.secretFullPath is required (e.g. 'dev/service/app1')" .Values.vault_secret.secretFullPath -}}
{{- $parts := splitList "/" $full -}}
{{- $plen := len $parts -}}
{{- if lt $plen 3 -}}
  {{- fail (printf "vault_secret.secretFullPath must have at least 3 segments like 'dev/service/app1', got '%s'" $full) -}}
{{- end -}}
{{- $computedMount := printf "%s/%s" (index $parts 0) (index $parts 1) -}}
{{- $computedPath  := join "/" (slice $parts 2 $plen) -}}

{{- $mount := default $computedMount .Values.vault_secret.mount -}}
{{- $path  := default $computedPath  .Values.vault_secret.path  -}}

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: "{{ include "common-chart.fullname" . }}-vss"
  labels:
    {{- include "common-chart.labels" . | nindent 4 }}
spec:
  vaultAuthRef: "{{ include "common-chart.fullname" . }}-va"
  mount: {{ $mount }}
  type: {{ .Values.vault_secret.type | default "kv-v1" }}
  path: {{ $path }}
  refreshAfter: {{ .Values.vault_secret.refreshAfter | default "30s" }}
  destination:
    create: true
    overwrite: true
    name: {{ required "values.vault_secret.name is required (k8s Secret name)" .Values.vault_secret.name }}

{{- end }}
