apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common-chart.fullname" . }}
  labels:
    {{- include "common-chart.labels" . | nindent 4 }}
  {{- if and .Values.reloader.enabled .Values.vault_secret.enabled .Values.vault_secret.name }}
  annotations:
    secret.reloader.stakater.com/reload: "{{ .Values.vault_secret.name }}"
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common-chart.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "common-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}{{ if .Values.image.tag }}:{{ .Values.image.tag }}{{ end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if and .Values.vault_secret.enabled .Values.vault_secret.attach.asEnv .Values.vault_secret.name }}
          envFrom:
            - secretRef:
                name: {{ .Values.vault_secret.name }}
          {{- end }}
          ports:
            {{- toYaml .Values.container.ports | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- $needSecretVol := and .Values.vault_secret.enabled .Values.vault_secret.attach.asVolume .Values.vault_secret.name }}
          {{- if or $needSecretVol .Values.volumeMounts }}
          volumeMounts:
            {{- if $needSecretVol }}
            - name: vault-secret
              mountPath: {{ .Values.vault_secret.attach.mountPath }}
              readOnly: true
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      {{- $needSecretVol := and .Values.vault_secret.enabled .Values.vault_secret.attach.asVolume .Values.vault_secret.name }}
      {{- if or $needSecretVol .Values.volumes }}
      volumes:
        {{- if $needSecretVol }}
        - name: vault-secret
          secret:
            secretName: {{ .Values.vault_secret.name }}
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
