{{- if .Values.vault_secret.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: "{{ include "common-chart.fullname" . }}-va"
  labels:
    {{- include "common-chart.labels" . | nindent 4 }}
spec:
  vaultConnectionRef: {{ .Values.vault_secret.vaultConnectionRef }}
  method: kubernetes
  mount: {{ .Values.vault_secret.authMount }}
  kubernetes:
    role: {{ default "ns-scoped-read" .Values.vault_secret.role }}
    serviceAccount: {{ include "common-chart.serviceAccountName" . }}
    {{- if .Values.vault_secret.audiences }}
    audiences:
      {{- toYaml .Values.vault_secret.audiences | nindent 6 }}
    {{- else }}
    audiences:
      - "https://kubernetes.default.svc"
    {{- end }}
{{- end }}
