! Configuration File for keepalived

global_defs {
  script_user       root
  script_security   on

!notification_email {
!     an@test.ru
!}

!notification_email_from keepalived@{{ ansible_hostname }}.test.ru
!   smtp_server 192.168.1.56
!   smtp_connect_timeout 30
}

# 1) Проверяем haproxy
vrrp_script chk_haproxy {
    script    "/usr/bin/pgrep haproxy"
    interval 2
    fall     2
    rise     1
    weight   20          # при успехе добавляем +20 к priority
}



vrrp_instance VI_1 {
    state {{ keepalived_check }}
    # Use the primary network interface detected by Ansible.  This avoids
    # hard‑coding interface names like enp0s3 and makes the configuration
    # portable across different distributions and cloud providers.
    interface {{ ansible_default_ipv4.interface }}
    garp_master_refresh 15
    virtual_router_id {{ keepalived_id }}
    priority {{ keepalived_priority_check }}
    advert_int 5
    smtp_alert
    authentication {
        auth_type PASS
        auth_pass 111werfgfgqwer3gfh567
    }
    virtual_ipaddress {
        {{ virtual_ip }} dev {{ ansible_default_ipv4.interface }} label {{ ansible_default_ipv4.interface }}:vip
    }
    track_script {
       chk_haproxy
    }
}
