scope: {{ patroni_cluster_name }}
name: {{patroni_check}}

restapi:
  listen: {{ ansible_default_ipv4.address }}:8008
  connect_address: {{ ansible_default_ipv4.address }}:8008

etcd:
  hosts: {{etcd1}}:2379, {{etcd2}}:2379, {{etcd3}}:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        wal_keep_segments: 8
        max_wal_senders: 5
        max_replication_slots: 5
        checkpoint_timeout: 30

  initdb:
  - encoding: UTF8
  - data-checksums

  pg_hba:
  - host replication repl {{patroni1}}/32 md5
  - host replication repl {{patroni2}}/32 md5
  - host all all {{patroni1}}/32 md5
  - host all all {{patroni2}}/32 md5

  users:
      dba:
        password: secret
        options:
            - createrole
            - createdb
      repl:
         password: secret
         options:
             - replication
             - replication

postgresql:
  listen: {{ ansible_default_ipv4.address }}:5432
  connect_address: {{ ansible_default_ipv4.address }}:5432
  data_dir: /var/lib/pgsql/10/data
  config_dir: /var/lib/pgsql/10/data
  bin_dir: /usr/pgsql-10/bin
  authentication:
    replication:
      username: repl
      password: pass
    superuser:
      username: postgres
      password: pass
  parameters:
    unix_socket_directories: '.'

