---

- name: reload minio systemd
  systemd:
    name: minio
    daemon_reload: True

- name: restart minio
  service:
    name: minio
    state: restarted

- name: Restart Keepalived
  service:
    name: keepalived
    state: restarted
    enabled: yes
  when: inventory_hostname in groups['minio'] and ansible_distribution in ['Debian', 'Ubuntu']
