- name: Task to install  gitlab, gitlab-runner, gitlab-registry
  hosts: gitlab
  become: true
  ignore_errors: no
  become_method: sudo
  gather_facts: yes
  vars:
   - gitlabrunner: true
   - proxy: false
   - proxyIP: "9.9.9.9:3128"
   - docker_package_state: latest
   - docker_install_compose: True
   - docker_compose_version: "1.22.0"
   - docker_compose_path: /usr/local/bin/docker-compose
  roles:
    - gitlab-gitlab-runner
