---
- hosts: all_servers
  become: true
  ignore_errors: no
  become_method: sudo
  gather_facts: yes
  vars:
   - proxy: false
   - proxyIP: "192.168.1.179:3128"
   - ansible_playbook_dir: /etc/ansible/
  roles:
   - new_server

