---
- hosts: nfs
  become: true
  ignore_errors: yes
  become_method: sudo
  gather_facts: yes
  vars:
   - dir_nfs_master: /nfs
   - dir_nfs_client: /nfs-client
   - k8s_nfs_provision: false # if true nfs client directory will not create
  roles:
    - nfs
